### ISSUE TITLE
Please make compatible with GNOME Shell 3.24

### ISSUE THREAD

**Issue by jbicha** [vibou/vibou.gTile#58] opened 2017-02-23 14:24 UTC
GNOME Shell 3.23.90 on Ubuntu GNOME 17.04 Beta

GNOME Shell 3.24 now uses mozjs38 (SpiderMonkey 38) which has stricter syntax rules.

Test Case
-------------
Run `gnome-shell-extension-prefs`
Click the gear button next to gTile.

The output is
```
TypeError: redeclaration of formal parameter iter

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._extensionFound/<@resource:///org/gnome/shell/extensionPrefs/main.js:206:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
```

**Comment by scherepanov** [comment] 2017-04-04 19:23
This iter is defined in lambda, not obvious (for me) how to fix. Also, Ubuntu GNOME 17.04 is not stable enough, at least refuses to start on my PC after upgrade.

**Comment by jbicha** [comment] 2017-04-05 12:44
I'm sorry to hear about your upgrade problem. Could you file a bug in Launchpad about that if you are still affected?

Fedora 24 Alpha was also released yesterday with GNOME 3.24.

I don't know much about gjs. You could try asking on IRC in #gnome-shell or ask the gjs maintainer, Philip Chimento.

**Comment by scherepanov** [comment] 2017-04-09 15:18
I fixed gTile for 3.24, check in my branch.
Seems to be cannot create additional pull request till previous will be done.

**Comment by jbicha** [comment] 2017-04-09 16:12
@scherepanov Why are you making this GPL-3? Arguably, it should be GPL-2+ since that's what gnome-shell is. It should be a separate commit also.

If you use multiple branches, you can make multiple pull requests in GitHub.

**Comment by scherepanov** [comment] 2017-04-09 16:57
Have no clue for various gpl flavor differences
I just saw gnome on ubuntu 17.04 is GPL v3, so I made it same
Will change to GPL v2+, have absolutely no preference
This commit sits on top of my previous commit that is not merged yet, not
possible to make independent pull request. Will have to wait till
maintainer will merge first commit.

**Comment by jbicha** [comment] 2017-04-09 17:05
> I just saw gnome on ubuntu 17.04 is GPL v3

Could you be more specific?

**Comment by scherepanov** [comment] 2017-04-09 21:10
Well, it looks like gnome is gpl. I was using gnome-shell extension taskbar  as an example, and on license page it says GPL but have a very big logo of GPL v3. So I thought gnome standard is gpl v3.
I change license text to gpl no version) and forced commit with change.
Anyway, I am not a maintainer of this code, need to wait till pull request will be executed.

**Comment by jbicha** [comment] 2017-04-09 21:50
I still have no idea what you're talking about with GNOME being GPLv3.

**Comment by scherepanov** [comment] 2017-04-09 21:51
That was a confusion caused by gpl v3 logo on "taskbar" extension

**Comment by jbicha** [comment] 2017-04-09 21:59
I'm obviously not the maintainer but I think it would be better if you would move the license change to a different merge proposal. Thanks!

**Closed** 2017-07-28 14:27 UTC
